In [1]:
import numpy as np
from scipy.linalg import logm, expm
np.set_printoptions(suppress = True)

In [2]:
# http://rsso02.psa.gov.ph/article/highlights-isabelas-population-count-2020-census-population-and-housing-2020-cph

ilagan_growth_rate = 1.77

Mactan Island

In [3]:
raw_T1_18 = np.array([[1617.75, 185.31, 1191.51, 12.51],
                      [216.90, 154.62, 222.93, 10.44],
                      [425.61, 152.64, 1461.69, 5.22],
                      [130.59, 71.01, 101.61, 341.73]])

In [4]:
T1_18 = raw_T1_18 / np.sum(raw_T1_18, axis = 1)[:, np.newaxis]
T1_18

array([[0.53798037, 0.06162457, 0.39623489, 0.00416018],
       [0.35857759, 0.25561672, 0.36854635, 0.01725934],
       [0.20810597, 0.07463475, 0.71470692, 0.00255237],
       [0.20248395, 0.11010327, 0.15754954, 0.52986324]])

In [5]:
np.sum(T1_18, axis = 1)

array([1., 1., 1., 1.])

In [6]:
# https://psa.gov.ph/content/highlights-region-vii-central-visayas-population-2020-census-population-and-housing-2020-cph

lapu_lapu_growth_rate = 4.26
t1 = int((18 * lapu_lapu_growth_rate) / ilagan_growth_rate)
t1

43

In [7]:
T1 = expm((logm(T1_18) / t1))
T1

array([[0.98196915, 0.00252176, 0.01538722, 0.00012188],
       [0.02068903, 0.96507367, 0.01322724, 0.00101006],
       [0.00714225, 0.00369826, 0.9891441 , 0.0000154 ],
       [0.00628236, 0.00615036, 0.00236204, 0.98520523]])

In [8]:
np.sum(T1, axis = 1)

array([1., 1., 1., 1.])

In [9]:
np.linalg.matrix_power(T1, t1)

array([[0.53798037, 0.06162457, 0.39623489, 0.00416018],
       [0.35857759, 0.25561672, 0.36854635, 0.01725934],
       [0.20810597, 0.07463475, 0.71470692, 0.00255237],
       [0.20248395, 0.11010327, 0.15754954, 0.52986324]])

In [10]:
np.save('Transitions/run1', T1)

Laguna de Bay

In [11]:
T2_15 = np.array([[0.7417, 0.2372, 0.0211, 0.0000],
                  [0.3118, 0.5745, 0.1137, 0.0000],
                  [0.0000, 0.0000, 1.0000, 0.0000],
                  [0.0000, 0.0000, 0.0000, 1.0000]])

In [12]:
np.sum(T2_15, axis = 1)

array([1., 1., 1., 1.])

In [13]:
# https://psa.gov.ph/content/highlights-region-iv-calabarzon-population-2020-census-population-and-housing-2020-cph

laguna_growth_rate = 2.30
t2 = int((15 * laguna_growth_rate) / ilagan_growth_rate)
t2

19

In [14]:
T2 = expm((logm(T2_15) / t2))
T2

array([[0.9801597 , 0.01975707, 0.00008323, 0.        ],
       [0.02597071, 0.96623314, 0.00779615, 0.        ],
       [0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ]])

In [15]:
np.sum(T2, axis = 1)

array([1., 1., 1., 1.])

In [16]:
np.linalg.matrix_power(T2, t2)

array([[0.7417, 0.2372, 0.0211, 0.    ],
       [0.3118, 0.5745, 0.1137, 0.    ],
       [0.    , 0.    , 1.    , 0.    ],
       [0.    , 0.    , 0.    , 1.    ]])

In [17]:
np.save('Transitions/run2.npy', T2)

Baroro Watershed

In [18]:
T3_12 = np.array([[0.7594, 0.2298, 0.0108, 0.0000],
                  [0.3526, 0.5758, 0.0716, 0.0000],
                  [0.0000, 0.0000, 1.0000, 0.0000],
                  [0.0000, 0.0000, 0.0000, 1.0000]])

In [19]:
np.sum(T3_12, axis = 1)

array([1., 1., 1., 1.])

In [20]:
# https://psa.gov.ph/content/highlights-region-i-ilocos-region-population-2020-census-population-and-housing-2020-cph

la_union_growth_rate = 0.94
t3 = int((12 * la_union_growth_rate) / ilagan_growth_rate)
t3

6

In [21]:
T3 = expm((logm(T3_12) / t3))
T3

array([[0.94320516, 0.05672058, 0.00007426, 0.        ],
       [0.0870308 , 0.89788793, 0.01508127, 0.        ],
       [0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ]])

In [22]:
np.sum(T3, axis = 1)

array([1., 1., 1., 1.])

In [23]:
np.linalg.matrix_power(T3, t3)

array([[0.7594, 0.2298, 0.0108, 0.    ],
       [0.3526, 0.5758, 0.0716, 0.    ],
       [0.    , 0.    , 1.    , 0.    ],
       [0.    , 0.    , 0.    , 1.    ]])

In [24]:
np.save('Transitions/run3', T3)